export type GlossaryTerm = {
  id: string
  term: string
  short: string
  body: string
  moduleIds?: string[]
}

/** Expanded glossary aligned with the M1–M8 pathway. */
export const GLOSSARY: GlossaryTerm[] = [
  {
    id: 'packet',
    term: 'Packet',
    short: 'A small chunk of data with addressing info sent across a network.',
    body: 'The Internet splits messages into packets so many users can share links, routes can adapt, and losses can be limited to pieces of a message rather than the whole transfer.',
    moduleIds: ['m1'],
  },
  {
    id: 'latency',
    term: 'Latency',
    short: 'Delay — how long it takes data to get where it needs to go.',
    body: 'Often discussed as the time until a response begins to matter. Distinct from bandwidth (capacity). Interactive apps are especially sensitive to latency and round-trip time.',
    moduleIds: ['m1', 'm2', 'm8'],
  },
  {
    id: 'bandwidth',
    term: 'Bandwidth',
    short: 'How much data can be transferred per unit time.',
    body: 'Think of hose thickness. High bandwidth can still feel slow if latency is high, because interactive protocols wait on round trips.',
    moduleIds: ['m1'],
  },
  {
    id: 'router',
    term: 'Router',
    short: 'A device that forwards packets toward their destinations between networks.',
    body: 'Routers read addressing information and choose the next hop. The Internet is a cooperative web of such forwarding decisions.',
    moduleIds: ['m1'],
  },
  {
    id: 'hop',
    term: 'Hop',
    short: 'One step in a packet’s path from one network device to the next.',
    body: 'Each hop can add processing, queueing, and distance. End-to-end latency is the sum of many small contributions.',
    moduleIds: ['m1', 'm7'],
  },
  {
    id: 'rtt',
    term: 'RTT (round-trip time)',
    short: 'Time for a request to go to a destination and a response to return.',
    body: 'Critical for calls, games, and many web protocols. GEO satellite Internet historically suffered large RTTs due to distance; LEO aims to shrink the space segment contribution.',
    moduleIds: ['m1', 'm2', 'm8'],
  },
  {
    id: 'client-server',
    term: 'Client–server',
    short: 'Pattern where a client initiates requests and a server responds.',
    body: 'Browsers, games, and apps act as clients; services in data centers respond. Most consumer Internet use follows this model.',
    moduleIds: ['m1'],
  },
  {
    id: 'geo',
    term: 'GEO',
    short: 'Geostationary orbit — ~35,786 km, appears fixed over the equator.',
    body: 'Satellites match Earth’s rotation and stay fixed in the sky from the ground. Huge footprints, few satellites needed for wide coverage, but large light-time delay.',
    moduleIds: ['m2'],
  },
  {
    id: 'leo',
    term: 'LEO',
    short: 'Low Earth Orbit — typically under ~2,000 km altitude.',
    body: 'Satellites move fast (~7.5–7.8 km/s) with periods around ~90–100 minutes. Lower latency than GEO, but continuous service needs a constellation.',
    moduleIds: ['m3'],
  },
  {
    id: 'meo',
    term: 'MEO',
    short: 'Medium Earth Orbit — between LEO and GEO (e.g. navigation constellations).',
    body: 'Used by systems such as GPS and Galileo. Latency and coverage sit between LEO and GEO extremes.',
    moduleIds: ['m3'],
  },
  {
    id: 'orbital-period',
    term: 'Orbital period',
    short: 'Time to complete one orbit.',
    body: 'For circular orbits, period grows with altitude. LEO periods are on the order of 90 minutes; GEO is about one sidereal day.',
    moduleIds: ['m3'],
  },
  {
    id: 'propagation-delay',
    term: 'Propagation delay',
    short: 'Time for a signal to travel through a medium at finite speed.',
    body: 'Bounded by the speed of light (or less in fiber). GEO’s altitude forces large propagation delay; LEO reduces it dramatically for the space hop.',
    moduleIds: ['m2', 'm3'],
  },
  {
    id: 'constellation',
    term: 'Constellation',
    short: 'A coordinated group of satellites providing a service together.',
    body: 'For LEO broadband, many satellites form a coverage net so users remain connected as individual satellites rise and set.',
    moduleIds: ['m3', 'm5'],
  },
  {
    id: 'shell',
    term: 'Shell',
    short: 'A set of satellites at a common design altitude (and related geometry).',
    body: 'Mega-constellations often use multiple shells for different inclinations, missions, or capacity layers.',
    moduleIds: ['m5'],
  },
  {
    id: 'orbital-plane',
    term: 'Orbital plane',
    short: 'The flat disk containing a satellite’s orbital path.',
    body: 'Constellations use many planes rotated around Earth so coverage wraps longitudes as well as latitudes.',
    moduleIds: ['m5'],
  },
  {
    id: 'inclination',
    term: 'Inclination',
    short: 'Tilt of an orbit relative to Earth’s equator.',
    body: 'Affects which latitudes get frequent coverage. Polar and high-inclination planes help high-latitude users.',
    moduleIds: ['m5'],
  },
  {
    id: 'phasing',
    term: 'Phasing',
    short: 'Relative spacing of satellites along an orbit or among planes.',
    body: 'Even phasing reduces clustering and coverage holes. Structured patterns (e.g. Walker-style ideas) formalize this.',
    moduleIds: ['m5'],
  },
  {
    id: 'raan',
    term: 'RAAN',
    short: 'Right ascension of the ascending node — orientation of an orbital plane.',
    body: 'A technical parameter describing how a plane is rotated around Earth. Spreading RAAN separates planes geographically.',
    moduleIds: ['m5'],
  },
  {
    id: 'walker',
    term: 'Walker constellation',
    short: 'A classic structured pattern for distributing satellites across planes.',
    body: 'Used as an accessible reference model in textbooks. Real operators may use Walker-like ideas without matching any specific public pattern exactly.',
    moduleIds: ['m5'],
  },
  {
    id: 'station-keeping',
    term: 'Station-keeping',
    short: 'Maneuvers that keep a satellite near its assigned orbit and slot.',
    body: 'Essential in dense LEO where drag and perturbations would otherwise ruin spacing, coverage, and safety.',
    moduleIds: ['m4'],
  },
  {
    id: 'ion-thruster',
    term: 'Ion thruster',
    short: 'Electric propulsion that accelerates ions for efficient low thrust.',
    body: 'Useful for long-duration station-keeping and gradual orbit raising on small satellites.',
    moduleIds: ['m4'],
  },
  {
    id: 'deorbit',
    term: 'Deorbit',
    short: 'Leaving operational orbit to re-enter and dispose of a satellite.',
    body: 'Critical for space safety in mega-constellations. Lower altitudes can shorten passive decay if propulsion fails.',
    moduleIds: ['m4'],
  },
  {
    id: 'phased-array',
    term: 'Phased array',
    short: 'Antenna made of many elements that steers beams electronically.',
    body: 'Enables flat user terminals to track fast LEO satellites without mechanically slewing a large dish.',
    moduleIds: ['m6'],
  },
  {
    id: 'handoff',
    term: 'Handoff (handover)',
    short: 'Switching a user from one serving satellite to another.',
    body: 'Required in LEO because satellites move quickly across the sky. Good systems aim to switch with minimal disruption.',
    moduleIds: ['m6', 'm8'],
  },
  {
    id: 'elevation',
    term: 'Elevation angle',
    short: 'How high a satellite appears above the horizon from the user.',
    body: 'Networks often require a minimum elevation for reliable service. Low elevation means longer atmospheric paths and more blockage risk.',
    moduleIds: ['m6'],
  },
  {
    id: 'user-terminal',
    term: 'User terminal',
    short: 'The customer antenna/modem on the ground (e.g. a flat Starlink dish).',
    body: 'Establishes and maintains the radio link to serving satellites using electronically steered beams in modern LEO systems.',
    moduleIds: ['m6'],
  },
  {
    id: 'footprint',
    term: 'Footprint',
    short: 'The region on Earth a satellite can serve at a given time.',
    body: 'Higher altitude generally means a larger footprint but more latency. LEO footprints move quickly as satellites orbit.',
    moduleIds: ['m2', 'm5', 'm6'],
  },
  {
    id: 'isl',
    term: 'ISL (inter-satellite link)',
    short: 'A communications link between satellites — often optical lasers.',
    body: 'Lets traffic route through a space mesh before descending to a ground gateway, improving long-haul and remote coverage options.',
    moduleIds: ['m7'],
  },
  {
    id: 'gateway',
    term: 'Gateway (ground station)',
    short: 'Ground facility connecting the satellite network to the terrestrial Internet.',
    body: 'Provides fiber on/off ramps. Without nearby gateways or ISLs, traffic would be constrained by ground infrastructure footprint.',
    moduleIds: ['m7'],
  },
  {
    id: 'routing',
    term: 'Routing',
    short: 'Choosing paths for packets through a network.',
    body: 'In LEO systems, routing may involve ISLs and gateways on a graph that changes as satellites move.',
    moduleIds: ['m7', 'm8'],
  },
  {
    id: 'bent-pipe',
    term: 'Bent-pipe',
    short: 'Architecture where a satellite mainly relays user traffic to a gateway.',
    body: 'Common mental model for classic GEO Internet: user ↔ satellite ↔ gateway ↔ Internet. LEO systems may also use space mesh routing.',
    moduleIds: ['m2', 'm7'],
  },
  {
    id: 'coverage-gap',
    term: 'Coverage gap',
    short: 'A time or place with no usable satellite in view.',
    body: 'Shows up in sparse constellations or with strict elevation masks. Mega-constellations are designed to minimize gaps for target users.',
    moduleIds: ['m3', 'm5'],
  },
  {
    id: 'beam-steering',
    term: 'Beam steering',
    short: 'Directing antenna energy toward a target direction.',
    body: 'Can be mechanical or electronic. Phased arrays steer electronically, which is key for tracking LEO satellites from flat terminals.',
    moduleIds: ['m6'],
  },
  {
    id: 'waypoint',
    term: 'Waypoint (orbit)',
    short: 'A temporary orbit used while raising or transferring satellites.',
    body: 'Used operationally to deconflict traffic and align orbital elements before joining a final service shell.',
    moduleIds: ['m4'],
  },
  {
    id: 'orbit-raise',
    term: 'Orbit raising',
    short: 'Propulsive climb from insertion altitude toward the service shell.',
    body: 'After launch, satellites often spend time raising altitude with electric propulsion before entering operational service.',
    moduleIds: ['m4'],
  },
  {
    id: 'ground-station',
    term: 'Ground station',
    short: 'Another name for gateway facilities that link space to terrestrial networks.',
    body: 'Houses antennas, RF equipment, and fiber connectivity for backhaul.',
    moduleIds: ['m7'],
  },
  {
    id: 'space-mesh',
    term: 'Space mesh',
    short: 'Network formed by satellites linked to each other (e.g. via lasers).',
    body: 'Enables multi-hop routing in orbit before traffic reaches a ground gateway.',
    moduleIds: ['m7'],
  },
  {
    id: 'scheduling',
    term: 'Scheduling (beams/resources)',
    short: 'Deciding which users/beams get radio resources when.',
    body: 'LEO systems must allocate scarce spectrum, power, and beam time across many users and moving cells.',
    moduleIds: ['m8'],
  },
  {
    id: 'performance',
    term: 'Performance (network)',
    short: 'User-visible outcomes: latency, throughput, loss, stability.',
    body: 'Emerges from geometry, RF, routing, congestion, and handovers — not from any single subsystem alone.',
    moduleIds: ['m8'],
  },
]

export function getTerm(id: string): GlossaryTerm | undefined {
  return GLOSSARY.find((t) => t.id === id)
}
