export type GlossaryTerm = {
  id: string
  term: string
  short: string
  body: string
  moduleIds?: string[]
  relatedIds?: string[]
}

/** Expanded glossary aligned with the full pathway. */
export const GLOSSARY: GlossaryTerm[] = [
  {
    id: 'packet',
    term: 'Packet',
    short: 'A small chunk of data with addressing info sent across a network.',
    body: 'The Internet splits messages into packets so many users can share links, routes can adapt, and losses can be limited to pieces of a message rather than the whole transfer.',
    moduleIds: ['m1'],
    relatedIds: ['router', 'hop', 'latency'],
  },
  {
    id: 'latency',
    term: 'Latency',
    short: 'Delay — how long it takes data to get where it needs to go.',
    body: 'Often discussed as the time until a response begins to matter. Distinct from bandwidth (capacity). Interactive apps are especially sensitive to latency and round-trip time.',
    moduleIds: ['m1', 'm2', 'm8'],
    relatedIds: ['bandwidth', 'rtt', 'propagation-delay'],
  },
  {
    id: 'bandwidth',
    term: 'Bandwidth',
    short: 'How much data can be transferred per unit time.',
    body: 'Think of hose thickness. High bandwidth can still feel slow if latency is high, because interactive protocols wait on round trips. ISP “speed” marketing usually means bandwidth.',
    moduleIds: ['m1'],
    relatedIds: ['latency', 'rtt'],
  },
  {
    id: 'router',
    term: 'Router',
    short: 'A device that forwards packets toward their destinations between networks.',
    body: 'Routers read addressing information and choose the next hop. The Internet is a cooperative web of such forwarding decisions.',
    moduleIds: ['m1'],
    relatedIds: ['hop', 'packet'],
  },
  {
    id: 'hop',
    term: 'Hop',
    short: 'One step in a packet’s path from one network device to the next.',
    body: 'Each hop can add processing, queueing, and distance. End-to-end latency is the sum of many small contributions.',
    moduleIds: ['m1', 'm7'],
    relatedIds: ['router', 'latency'],
  },
  {
    id: 'rtt',
    term: 'RTT (round-trip time)',
    short: 'Time for a request to go to a destination and a response to return.',
    body: 'Critical for calls, games, and many web protocols. GEO satellite Internet historically suffered large RTTs due to distance; LEO aims to shrink the space segment contribution.',
    moduleIds: ['m1', 'm2', 'm8'],
    relatedIds: ['latency', 'propagation-delay'],
  },
  {
    id: 'client-server',
    term: 'Client–server',
    short: 'Pattern where a client initiates requests and a server responds.',
    body: 'Browsers, games, and apps act as clients; services in data centers respond. Most consumer Internet use follows this model — and often needs at least one RTT per useful exchange.',
    moduleIds: ['m1'],
    relatedIds: ['rtt', 'packet'],
  },
  {
    id: 'ip',
    term: 'IP (Internet Protocol)',
    short: 'Addressing and hop-by-hop packet delivery on the Internet.',
    body: 'IP delivers packets “best effort” — they can be delayed, dropped, or reordered. Higher layers (like TCP) add reliability when apps need it. Satellite links still carry ordinary IP.',
    moduleIds: ['m1'],
    relatedIds: ['packet', 'tcp'],
  },
  {
    id: 'tcp',
    term: 'TCP',
    short: 'Reliable stream protocol that rides on IP packets.',
    body: 'TCP orders data, retransmits losses, and controls congestion. The connection handshake costs about one RTT before app data — high latency multiplies that cost.',
    moduleIds: ['m1'],
    relatedIds: ['ip', 'rtt'],
  },
  {
    id: 'dns',
    term: 'DNS',
    short: 'System that maps human domain names to IP addresses.',
    body: 'Before your browser can talk to a server by name, DNS resolves the name to an address. That lookup itself can add latency on cold starts.',
    moduleIds: ['m1'],
    relatedIds: ['ip', 'latency'],
  },
  {
    id: 'geo',
    term: 'GEO',
    short: 'Geostationary orbit — ~35,786 km, appears fixed over the equator.',
    body: 'Satellites match Earth’s rotation and stay fixed in the sky from the ground. Huge footprints, few satellites needed for wide coverage, but large light-time delay. Strictly: geostationary = geosynchronous + equatorial.',
    moduleIds: ['m2'],
    relatedIds: ['leo', 'meo', 'propagation-delay', 'footprint'],
  },
  {
    id: 'leo',
    term: 'LEO',
    short: 'Low Earth Orbit — typically under ~2,000 km altitude.',
    body: 'Satellites move fast (~7.5–7.8 km/s) with periods around ~90–100 minutes. Lower latency than GEO, but continuous service needs a constellation. Practical lower floor is set by atmospheric drag (~160–180 km).',
    moduleIds: ['m3'],
    relatedIds: ['geo', 'meo', 'constellation', 'orbital-period'],
  },
  {
    id: 'meo',
    term: 'MEO',
    short: 'Medium Earth Orbit — between LEO and GEO (e.g. navigation constellations).',
    body: 'Used by systems such as GPS and Galileo (~20,000 km class). Latency and coverage sit between LEO and GEO extremes.',
    moduleIds: ['m3'],
    relatedIds: ['leo', 'geo'],
  },
  {
    id: 'ngso',
    term: 'NGSO',
    short: 'Non-geostationary satellite orbit — satellites that move relative to the ground.',
    body: 'LEO and MEO systems are NGSO. Regulatory filings often contrast NGSO mega-constellations with traditional GSO/GEO systems.',
    moduleIds: ['m3', 'm5'],
    relatedIds: ['leo', 'geo'],
  },
  {
    id: 'orbital-period',
    term: 'Orbital period',
    short: 'Time to complete one orbit.',
    body: 'For circular orbits, period grows with altitude (Kepler’s third law). LEO periods are on the order of 90 minutes; GEO is about one sidereal day (~23 h 56 m), not exactly 24 h solar.',
    moduleIds: ['m3'],
    relatedIds: ['leo', 'geo'],
  },
  {
    id: 'propagation-delay',
    term: 'Propagation delay',
    short: 'Time for a signal to travel through a medium at finite speed.',
    body: 'Bounded by the speed of light (or less in fiber). GEO’s altitude forces large propagation delay; LEO reduces it dramatically for the space hop. Real RTT also includes processing and queues.',
    moduleIds: ['m2', 'm3'],
    relatedIds: ['latency', 'rtt'],
  },
  {
    id: 'constellation',
    term: 'Constellation',
    short: 'A coordinated group of satellites providing a service together.',
    body: 'For LEO broadband, many satellites form a coverage net so users remain connected as individual satellites rise and set.',
    moduleIds: ['m3', 'm5'],
    relatedIds: ['shell', 'orbital-plane', 'coverage-gap'],
  },
  {
    id: 'shell',
    term: 'Shell',
    short: 'A set of satellites at a common design altitude (and related geometry).',
    body: 'Mega-constellations often use multiple shells for different inclinations, missions, or capacity layers. Public Starlink planning separates broadband and direct-to-cell bands.',
    moduleIds: ['m5'],
    relatedIds: ['constellation', 'inclination', 'orbital-plane'],
  },
  {
    id: 'orbital-plane',
    term: 'Orbital plane',
    short: 'The flat disk containing a satellite’s orbital path.',
    body: 'Constellations use many planes rotated around Earth so coverage wraps longitudes as well as latitudes.',
    moduleIds: ['m5'],
    relatedIds: ['inclination', 'raan', 'phasing'],
  },
  {
    id: 'inclination',
    term: 'Inclination',
    short: 'Tilt of an orbit relative to Earth’s equator.',
    body: 'Affects which latitudes get frequent coverage. Polar and high-inclination planes help high-latitude users.',
    moduleIds: ['m5'],
    relatedIds: ['orbital-plane', 'shell'],
  },
  {
    id: 'phasing',
    term: 'Phasing',
    short: 'Relative spacing of satellites along an orbit or among planes.',
    body: 'Even phasing reduces clustering and coverage holes. Structured patterns (e.g. Walker-style ideas) formalize this.',
    moduleIds: ['m5'],
    relatedIds: ['walker', 'orbital-plane'],
  },
  {
    id: 'raan',
    term: 'RAAN',
    short: 'Right ascension of the ascending node — orientation of an orbital plane.',
    body: 'A technical parameter describing how a plane is rotated around Earth. Spreading RAAN separates planes geographically.',
    moduleIds: ['m5'],
    relatedIds: ['orbital-plane'],
  },
  {
    id: 'walker',
    term: 'Walker constellation',
    short: 'A classic structured pattern for distributing satellites across planes.',
    body: 'Used as an accessible reference model in textbooks. Real operators may use Walker-like ideas without matching any specific public pattern exactly.',
    moduleIds: ['m5'],
    relatedIds: ['constellation', 'phasing'],
  },
  {
    id: 'station-keeping',
    term: 'Station-keeping',
    short: 'Maneuvers that keep a satellite near its assigned orbit and slot.',
    body: 'Essential in dense LEO where drag and perturbations would otherwise ruin spacing, coverage, and safety.',
    moduleIds: ['m4'],
    relatedIds: ['ion-thruster', 'deorbit'],
  },
  {
    id: 'ion-thruster',
    term: 'Ion thruster',
    short: 'Electric propulsion that accelerates ions for efficient low thrust.',
    body: 'Useful for long-duration station-keeping and gradual orbit raising on small satellites. Public Starlink materials describe argon thrusters on later vehicles; earlier generations used krypton (industry reporting).',
    moduleIds: ['m4'],
    relatedIds: ['station-keeping', 'orbit-raise'],
  },
  {
    id: 'deorbit',
    term: 'Deorbit',
    short: 'Leaving operational orbit to re-enter and dispose of a satellite.',
    body: 'Critical for space safety in mega-constellations. Lower altitudes can shorten passive decay if propulsion fails. U.S. FCC licensing moved toward a 5-year LEO disposal norm for licensees.',
    moduleIds: ['m4', 'opt-debris'],
    relatedIds: ['station-keeping', 'shell'],
  },
  {
    id: 'waypoint',
    term: 'Waypoint (orbit)',
    short: 'A temporary orbit used while raising or transferring satellites.',
    body: 'Used operationally to deconflict traffic and align orbital elements before joining a final service shell.',
    moduleIds: ['m4'],
    relatedIds: ['orbit-raise', 'shell'],
  },
  {
    id: 'orbit-raise',
    term: 'Orbit raising',
    short: 'Propulsive climb from insertion altitude toward the service shell.',
    body: 'After launch, satellites often spend time raising altitude with electric propulsion before entering operational service.',
    moduleIds: ['m4'],
    relatedIds: ['waypoint', 'ion-thruster'],
  },
  {
    id: 'phased-array',
    term: 'Phased array',
    short: 'Antenna made of many elements that steers beams electronically.',
    body: 'By adjusting the phase of each element, the combined beam points without mechanically slewing a large dish — key for flat LEO user terminals.',
    moduleIds: ['m6'],
    relatedIds: ['beam-steering', 'user-terminal'],
  },
  {
    id: 'handoff',
    term: 'Handoff (handover)',
    short: 'Switching a user from one serving satellite to another.',
    body: 'Required in LEO because satellites move quickly across the sky. Good systems aim to switch with minimal disruption (often make-before-break when geometry allows).',
    moduleIds: ['m6', 'm8'],
    relatedIds: ['elevation', 'user-terminal'],
  },
  {
    id: 'elevation',
    term: 'Elevation angle',
    short: 'How high a satellite appears above the horizon from the user.',
    body: 'Networks often require a minimum elevation for reliable service. Low elevation means longer atmospheric paths and more blockage risk. Higher min elevation shrinks usable sky.',
    moduleIds: ['m6'],
    relatedIds: ['handoff', 'footprint', 'coverage-gap'],
  },
  {
    id: 'user-terminal',
    term: 'User terminal',
    short: 'The customer antenna/modem on the ground (e.g. a flat Starlink dish).',
    body: 'Establishes and maintains the radio link to serving satellites using electronically steered beams in modern LEO systems.',
    moduleIds: ['m6'],
    relatedIds: ['phased-array', 'handoff'],
  },
  {
    id: 'footprint',
    term: 'Footprint',
    short: 'The region on Earth a satellite can serve at a given time.',
    body: 'Higher altitude generally means a larger footprint but more latency. LEO footprints move quickly as satellites orbit.',
    moduleIds: ['m2', 'm5', 'm6'],
    relatedIds: ['elevation', 'coverage-gap'],
  },
  {
    id: 'isl',
    term: 'ISL (inter-satellite link)',
    short: 'A communications link between satellites — often optical lasers.',
    body: 'Lets traffic route through a space mesh before descending to a ground gateway, improving long-haul and remote coverage options. Public Starlink materials describe optical ISLs at high data rates.',
    moduleIds: ['m7'],
    relatedIds: ['gateway', 'space-mesh', 'routing'],
  },
  {
    id: 'gateway',
    term: 'Gateway (ground station)',
    short: 'Ground facility connecting the satellite network to the terrestrial Internet.',
    body: 'Provides fiber on/off ramps. Without nearby gateways or ISLs, traffic would be constrained by ground infrastructure footprint.',
    moduleIds: ['m7'],
    relatedIds: ['isl', 'ground-station', 'bent-pipe'],
  },
  {
    id: 'routing',
    term: 'Routing',
    short: 'Choosing paths for packets through a network.',
    body: 'In LEO systems, routing may involve ISLs and gateways on a graph that changes as satellites move. Exact operator algorithms are proprietary — we teach the problem class.',
    moduleIds: ['m7', 'm8'],
    relatedIds: ['isl', 'space-mesh', 'hop'],
  },
  {
    id: 'bent-pipe',
    term: 'Bent-pipe',
    short: 'Architecture where a satellite mainly relays user traffic to a gateway.',
    body: 'Common mental model for classic GEO Internet: user ↔ satellite ↔ gateway ↔ Internet. Transparent / bent-pipe payloads amplify and retransmit; regenerative payloads can process and route onboard.',
    moduleIds: ['m2', 'm7'],
    relatedIds: ['gateway', 'regenerative'],
  },
  {
    id: 'regenerative',
    term: 'Regenerative payload',
    short: 'Onboard processing that can decode, switch, or route traffic in space.',
    body: 'Contrasts with transparent bent-pipe relays. Regenerative designs pair naturally with multi-hop mesh routing, at the cost of complexity and power.',
    moduleIds: ['m7'],
    relatedIds: ['bent-pipe', 'isl', 'routing'],
  },
  {
    id: 'coverage-gap',
    term: 'Coverage gap',
    short: 'A time or place with no usable satellite in view.',
    body: 'Shows up in sparse constellations or with strict elevation masks. Mega-constellations are designed to minimize gaps for target users.',
    moduleIds: ['m3', 'm5'],
    relatedIds: ['constellation', 'elevation'],
  },
  {
    id: 'beam-steering',
    term: 'Beam steering',
    short: 'Directing antenna energy toward a target direction.',
    body: 'Can be mechanical or electronic. Phased arrays steer electronically, which is key for tracking LEO satellites from flat terminals.',
    moduleIds: ['m6'],
    relatedIds: ['phased-array'],
  },
  {
    id: 'ground-station',
    term: 'Ground station',
    short: 'Another name for gateway facilities that link space to terrestrial networks.',
    body: 'Houses antennas, RF equipment, and fiber connectivity for backhaul.',
    moduleIds: ['m7'],
    relatedIds: ['gateway'],
  },
  {
    id: 'space-mesh',
    term: 'Space mesh',
    short: 'Network formed by satellites linked to each other (e.g. via lasers).',
    body: 'Enables multi-hop routing in orbit before traffic reaches a ground gateway.',
    moduleIds: ['m7'],
    relatedIds: ['isl', 'routing'],
  },
  {
    id: 'scheduling',
    term: 'Scheduling (beams/resources)',
    short: 'Deciding which users/beams get radio resources when.',
    body: 'LEO systems must allocate scarce spectrum, power, and beam time across many users and moving cells. Exact schedules are proprietary.',
    moduleIds: ['m8'],
    relatedIds: ['performance', 'phased-array'],
  },
  {
    id: 'performance',
    term: 'Performance (network)',
    short: 'User-visible outcomes: latency, throughput, loss, stability.',
    body: 'Emerges from geometry, RF, routing, congestion, and handovers — not from any single subsystem alone. Separate geometric light-time floor from mean RTT, jitter, and outages.',
    moduleIds: ['m8'],
    relatedIds: ['latency', 'bandwidth', 'rtt', 'jitter'],
  },
  {
    id: 'jitter',
    term: 'Jitter',
    short: 'Variation in latency over time — how much delay wobbles.',
    body: 'Interactive apps care about smooth timing, not only average RTT. Handoffs, queues, path changes, and radio conditions can spike delay even when the geometric floor is low.',
    moduleIds: ['m1', 'm8'],
    relatedIds: ['latency', 'rtt', 'handoff', 'performance'],
  },
  {
    id: 'ku-band',
    term: 'Ku-band',
    short: 'Microwave band roughly 12–18 GHz, common for satellite user links.',
    body: 'Higher than older C-band consumer services; allows smaller antennas. Exact Starlink channel maps are regulatory/operator details — teach the band class, not reverse-engineered tables.',
    moduleIds: ['m6', 'm7'],
    relatedIds: ['ka-band', 'user-terminal'],
  },
  {
    id: 'ka-band',
    term: 'Ka-band',
    short: 'Microwave band roughly 26–40 GHz, often used for high-throughput feeder links.',
    body: 'More bandwidth potential than Ku, more rain fade. Public materials associate Ka/E-class links with gateway-side capacity on Starlink-class systems.',
    moduleIds: ['m7'],
    relatedIds: ['ku-band', 'gateway'],
  },
  {
    id: 'rain-fade',
    term: 'Rain fade',
    short: 'Signal loss when rain absorbs or scatters high-frequency radio waves.',
    body: 'Gets worse at higher frequencies (Ka, V, E). Link design and site diversity mitigate it; it is physics, not a software bug.',
    moduleIds: ['m7'],
    relatedIds: ['ka-band', 'ku-band'],
  },
  {
    id: 'link-budget',
    term: 'Link budget',
    short: 'Accounting of power, gains, and losses that determine if a radio link works.',
    body: 'Distance, antenna gain, frequency, weather, and noise all enter. Direct-to-cell is harder than dish broadband mainly because phone antennas have far less gain.',
    moduleIds: ['m6', 'opt-dtc'],
    relatedIds: ['user-terminal', 'phased-array'],
  },
  {
    id: 'direct-to-cell',
    term: 'Direct-to-cell (DTC)',
    short: 'Satellite service aimed at ordinary phones, not dedicated dishes.',
    body: 'Different product class from dish broadband: tougher link budgets, often partnered with mobile operators, often messaging-first. Public Starlink planning places DTC shells in a lower altitude band.',
    moduleIds: ['opt-dtc'],
    relatedIds: ['link-budget', 'shell', 'user-terminal'],
  },
  {
    id: 'slant-range',
    term: 'Slant range',
    short: 'Straight-line distance from user to satellite (not just altitude).',
    body: 'At low elevation the path through space (and atmosphere) is longer than the satellite’s altitude. Light-time and link budgets use slant range, not nadir altitude alone.',
    moduleIds: ['m2', 'm6', 'opt-math'],
    relatedIds: ['elevation', 'propagation-delay'],
  },
  {
    id: 'sidereal-day',
    term: 'Sidereal day',
    short: 'Earth’s rotation period relative to the stars (~23 h 56 m).',
    body: 'GEO orbital period matches a sidereal day so the satellite stays fixed over one longitude. It is slightly shorter than the 24-hour solar day.',
    moduleIds: ['m2', 'opt-math'],
    relatedIds: ['geo', 'orbital-period'],
  },
  {
    id: 'pass',
    term: 'Pass',
    short: 'The time window when a satellite is usable above a minimum elevation.',
    body: 'LEO passes are short (minutes). Continuous service stitches many passes from many satellites via handovers.',
    moduleIds: ['m6'],
    relatedIds: ['elevation', 'handoff'],
  },
  {
    id: 'ephemeris',
    term: 'Ephemeris',
    short: 'Predicted positions of a satellite over time.',
    body: 'Operators and catalogs publish ephemerides so others can predict conjunctions and schedule observations. Accuracy matters for collision avoidance in dense LEO.',
    moduleIds: ['opt-debris', 'm4'],
    relatedIds: ['station-keeping', 'deorbit'],
  },
  {
    id: 'kessler',
    term: 'Kessler syndrome',
    short: 'Hypothetical cascade where collisions create debris that causes more collisions.',
    body: 'Physics is settled as a risk model; whether we are “in cascade now” is debated and model-dependent. Prefer “rising conjunction risk” language unless discussing the cascade concept carefully.',
    moduleIds: ['opt-debris'],
    relatedIds: ['deorbit', 'ephemeris'],
  },
  {
    id: 'spot-beam',
    term: 'Spot beam',
    short: 'A focused radio beam covering a limited ground cell, not the whole footprint.',
    body: 'LEO broadband systems serve users with many small beams (cells). That multiplies capacity via frequency reuse and creates scheduling and interference as design problems — not a single shared megaphone.',
    moduleIds: ['m5', 'm6'],
    relatedIds: ['capacity-density', 'phased-array', 'footprint'],
  },
  {
    id: 'capacity-density',
    term: 'Capacity density',
    short: 'How much aggregate user throughput a region can support, not just whether sats are visible.',
    body: 'Coverage is geometric (sats above elevation). Capacity depends on spectrum, power, beams, and how many users share them. Dense sky can still feel slow under load.',
    moduleIds: ['m5', 'm8'],
    relatedIds: ['spot-beam', 'coverage-gap', 'bandwidth'],
  },
  {
    id: 'obstruction',
    term: 'Obstruction',
    short: 'Something blocking the line of sight between terminal and satellite.',
    body: 'Trees, roofs, terrain, and vehicle bodies commonly cause outages even when a satellite is above the mathematical min elevation. Clear field of view is part of the system.',
    moduleIds: ['m6'],
    relatedIds: ['elevation', 'pass', 'user-terminal'],
  },
]

export function getTerm(id: string): GlossaryTerm | undefined {
  return GLOSSARY.find((t) => t.id === id)
}

export function getRelatedTerms(id: string): GlossaryTerm[] {
  const term = getTerm(id)
  if (!term?.relatedIds?.length) return []
  return term.relatedIds.map(getTerm).filter(Boolean) as GlossaryTerm[]
}
