export type GlossaryTerm = {
  id: string
  term: string
  short: string
  body: string
  moduleIds?: string[]
  relatedIds?: string[]
}

/**
 * Glossary for the full learning path.
 * Voice: plain language + practical units/scales so terms are usable, not just defined.
 */
export const GLOSSARY: GlossaryTerm[] = [
  {
    id: 'packet',
    term: 'Packet',
    short: 'A small labeled chunk of data sent across a network (often hundreds to a few thousand bytes each).',
    body: 'The Internet rarely sends a whole file as one giant blob. It splits the message into packets, each with a bit of payload plus addressing labels. Typical sizes are often on the order of hundreds to about 1,500 bytes on common paths (bigger is possible in special cases). Many people can share the same cables, and if one piece is lost you only resend that piece. Analogy: mailing a book as many sealed envelopes instead of one huge box.',
    moduleIds: ['m1'],
    relatedIds: ['router', 'hop', 'latency'],
  },
  {
    id: 'latency',
    term: 'Latency',
    short: 'Delay: how long you wait, usually measured in milliseconds (ms).',
    body: 'Latency is waiting time, not “how thick the pipe is.” It is almost always reported in milliseconds (ms). 1,000 ms = 1 second. Rough human feel: about 20 to 40 ms can feel snappy; around 100 to 200 ms is noticeable; 500 ms and up makes conversation awkward. A video call cares a lot about latency. A big download also cares about bandwidth (capacity). High bandwidth with high latency can still feel sluggish for interactive apps.',
    moduleIds: ['m1', 'm2', 'm8'],
    relatedIds: ['bandwidth', 'rtt', 'propagation-delay'],
  },
  {
    id: 'bandwidth',
    term: 'Bandwidth',
    short: 'How much data can flow per second (capacity), often in Mbps or Gbps.',
    body: 'Think of hose thickness. Network “speed” ads usually quote bandwidth in megabits per second (Mbps) or gigabits per second (Gbps). Note: bits, not bytes. 8 bits = 1 byte, so downloading a 10 MB file at 10 Mbps takes longer than 10 seconds in the ideal case (and real life is slower). A thick hose pours a lot of water, but if the hose is very long you still wait for the first water to arrive. High bandwidth is not the same as low latency.',
    moduleIds: ['m1'],
    relatedIds: ['latency', 'rtt'],
  },
  {
    id: 'router',
    term: 'Router',
    short: 'A device that forwards packets toward their destinations between networks.',
    body: 'A router reads the address on a packet and chooses the next stop, like a mail sorting office for bits. Home “routers” often also act as a WiFi access point and a switch. On the public Internet, a trip may pass through many routers; each stop is a hop that can add a little delay.',
    moduleIds: ['m1'],
    relatedIds: ['hop', 'packet'],
  },
  {
    id: 'hop',
    term: 'Hop',
    short: 'One step from one network device to the next along a path.',
    body: 'A trip across the Internet is a chain of hops, like changing trains. Tools such as traceroute list hops. Each hop can add a little waiting (machine work, queues, and travel distance), often from less than 1 ms to many milliseconds depending on distance and load. End to end delay is the sum of many small contributions.',
    moduleIds: ['m1', 'm7'],
    relatedIds: ['router', 'latency'],
  },
  {
    id: 'rtt',
    term: 'RTT (round trip time)',
    short: 'Time for a request to go out and a response to come back, measured in ms.',
    body: 'RTT is usually measured in milliseconds (ms), for example with ping. Many apps wait for a full round trip before they can continue. Rough feel: fiber home paths often land in tens of ms to a nearby server; classic GEO satellite user RTTs were often 500 to 700+ ms; LEO aims for much lower space delay, though the full path still adds ground network time. Video calls and games feel RTT strongly.',
    moduleIds: ['m1', 'm2', 'm8'],
    relatedIds: ['latency', 'propagation-delay'],
  },
  {
    id: 'client-server',
    term: 'Client server',
    short: 'A pattern where a client asks and a server answers.',
    body: 'Your browser, game, or app is often the client. A service in a data center is the server. Most everyday Internet use works this way. Useful work often needs at least one round trip (RTT) per exchange, so high delay multiplies how “chatty” protocols feel.',
    moduleIds: ['m1'],
    relatedIds: ['rtt', 'packet'],
  },
  {
    id: 'ip',
    term: 'IP (Internet Protocol)',
    short: 'The standard way the Internet addresses and delivers packets hop by hop.',
    body: 'IP is “best effort”: packets can be delayed, dropped, or reordered. Addresses look like IPv4 (for example 192.0.2.1) or longer IPv6 strings. When apps need reliability, higher layers such as TCP add it. Satellite links still carry ordinary IP packets. The medium changes; the labeling idea does not.',
    moduleIds: ['m1'],
    relatedIds: ['packet', 'tcp'],
  },
  {
    id: 'tcp',
    term: 'TCP',
    short: 'A common way to send a reliable stream of data over IP packets.',
    body: 'TCP puts packets in order, resends losses, and tries not to overload the network. Opening a TCP connection often costs about one full RTT of handshake before useful app data flows (on the order of tens of ms on good fiber, hundreds of ms on high delay paths). High bandwidth (Mbps) does not shrink that handshake. Only lower RTT does.',
    moduleIds: ['m1'],
    relatedIds: ['ip', 'rtt'],
  },
  {
    id: 'dns',
    term: 'DNS',
    short: 'The system that turns human website names into machine IP addresses.',
    body: 'You type a name like example.com. DNS looks up the numeric address your computer needs. That lookup itself can add delay the first time (a cold start), often a few to tens of milliseconds when nearby caches are warm, and more when they are not.',
    moduleIds: ['m1'],
    relatedIds: ['ip', 'latency'],
  },
  {
    id: 'geo',
    term: 'GEO',
    short: 'Geostationary orbit: about 35,786 km high, appears fixed over the equator.',
    body: 'A GEO satellite moves with Earth’s rotation so it can stay over one longitude and look glued in the sky from the ground. Huge coverage footprint means few satellites can serve wide areas. Pure light time up and down is about 240 ms when the satellite is overhead; real user RTT is often 500 to 700+ ms with gateways and processing. That is why classic satellite internet felt laggy for calls and games.',
    moduleIds: ['m2'],
    relatedIds: ['leo', 'meo', 'propagation-delay', 'footprint'],
  },
  {
    id: 'leo',
    term: 'LEO',
    short: 'Low Earth orbit: typically under about 2,000 km altitude.',
    body: 'LEO satellites move fast (about 7.5 to 7.8 km per second, or roughly 27,000 km/h) and loop Earth in roughly 90 minutes. At about 550 km straight overhead, pure one way light time is only about 1.8 ms (real user RTT is higher). Each satellite only covers you for a short pass of minutes. Continuous service needs a constellation (a coordinated fleet).',
    moduleIds: ['m3'],
    relatedIds: ['geo', 'meo', 'constellation', 'orbital-period'],
  },
  {
    id: 'meo',
    term: 'MEO',
    short: 'Medium Earth orbit: between LEO and GEO (for example many navigation systems).',
    body: 'GPS and Galileo style systems often live around the 20,000 km class (period on the order of 12 hours). One way light time is tens of milliseconds (roughly 67 ms at 20,000 km). Delay and coverage sit between LEO and GEO extremes.',
    moduleIds: ['m3'],
    relatedIds: ['leo', 'geo'],
  },
  {
    id: 'ngso',
    term: 'NGSO',
    short: 'Non geostationary satellite orbit: satellites that move relative to the ground.',
    body: 'LEO and MEO systems are NGSO. Regulators often contrast NGSO mega constellations with traditional GEO (geostationary) systems. For learners, the plain idea is: the satellite does not stay fixed in your sky, so handovers and dense fleets matter.',
    moduleIds: ['m3', 'm5'],
    relatedIds: ['leo', 'geo'],
  },
  {
    id: 'orbital-period',
    term: 'Orbital period',
    short: 'Time to complete one full loop around Earth (often minutes or hours).',
    body: 'For simple circular orbits, higher altitude means a longer period. LEO periods are often around 90 to 100 minutes (about 16 loops per day). GEO is about one sidereal day (about 23 hours 56 minutes), not exactly 24 solar hours. The lab and code alongs report period in minutes.',
    moduleIds: ['m3'],
    relatedIds: ['leo', 'geo'],
  },
  {
    id: 'propagation-delay',
    term: 'Propagation delay',
    short: 'Travel time for a signal, usually in ms, from t = distance / speed.',
    body: 'Radio and light cannot go infinitely fast. Empty space is about 300,000 km per second (about 299,792 km/s). Fiber glass is slower, roughly two thirds of that. Rule of thumb: one way light time is about 3.3 ms per 1,000 km in free space. GEO height forces about 119 ms one way overhead; LEO at 550 km is about 1.8 ms one way. Real user RTT still adds processing and queues on top.',
    moduleIds: ['m2', 'm3'],
    relatedIds: ['latency', 'rtt'],
  },
  {
    id: 'constellation',
    term: 'Constellation',
    short: 'A coordinated team of satellites providing a service together.',
    body: 'For LEO broadband, many satellites form a moving coverage net so you stay connected as one satellite sets and another rises. Fleet sizes for mega constellations are measured in thousands and change over time (always date your numbers). One LEO satellite alone is never enough for always on home service.',
    moduleIds: ['m3', 'm5'],
    relatedIds: ['shell', 'orbital-plane', 'coverage-gap'],
  },
  {
    id: 'shell',
    term: 'Shell',
    short: 'A layer of satellites at a shared design height (km above Earth) and related geometry.',
    body: 'Think of a layer of a cake around Earth. Heights are quoted in kilometers above the surface (for example hundreds of km for Starlink class broadband shells). Mega constellations often use several shells for different tilts, missions, or capacity. Public plans change; date the source.',
    moduleIds: ['m5'],
    relatedIds: ['constellation', 'inclination', 'orbital-plane'],
  },
  {
    id: 'orbital-plane',
    term: 'Orbital plane',
    short: 'A flat ring slice that contains one loop of satellite paths.',
    body: 'Imagine orange segments around Earth. Designers count planes and satellites per plane (for example 20 planes × 30 sats). Many planes rotated around the planet spread coverage in longitude as well as latitude.',
    moduleIds: ['m5'],
    relatedIds: ['inclination', 'raan', 'phasing'],
  },
  {
    id: 'inclination',
    term: 'Inclination',
    short: 'How tilted an orbit is relative to Earth’s equator, measured in degrees.',
    body: '0° is equatorial (stays near the equator). 90° is polar (passes over the poles). Public Starlink style shells use values such as about 43°, 53°, 70°, or near 97°. High tilt helps users far north or south. A low tilt plane spends more time near the equator.',
    moduleIds: ['m5'],
    relatedIds: ['orbital-plane', 'shell'],
  },
  {
    id: 'phasing',
    term: 'Phasing',
    short: 'How satellites are spaced along a plane or among planes (angles or timing).',
    body: 'Even spacing reduces clumping and coverage holes, like staggering bus departures so two buses do not arrive at once and leave a long gap later. Phasing is often described with angles around the orbit (degrees along the track).',
    moduleIds: ['m5'],
    relatedIds: ['walker', 'orbital-plane'],
  },
  {
    id: 'raan',
    term: 'RAAN',
    short: 'A technical angle (in degrees) that sets how an orbital plane is rotated around Earth.',
    body: 'Full name: right ascension of the ascending node. You can treat it as “which way the plane is spun around the planet,” measured as an angle from 0° to 360°. Spreading RAAN spreads planes geographically. Optional jargon; the idea of rotated planes matters more than the acronym.',
    moduleIds: ['m5'],
    relatedIds: ['orbital-plane'],
  },
  {
    id: 'walker',
    term: 'Walker constellation',
    short: 'A classic textbook pattern for distributing satellites across planes.',
    body: 'Useful as a teaching reference for “even spacing in a structured way,” often written with counts of planes and sats per plane. Real operators may use similar ideas without matching any specific public pattern exactly.',
    moduleIds: ['m5'],
    relatedIds: ['constellation', 'phasing'],
  },
  {
    id: 'station-keeping',
    term: 'Station keeping',
    short: 'Small thruster burns that keep a satellite near its assigned orbit and slot.',
    body: 'Low orbit is not a perfect vacuum. Thin air and other small forces nudge satellites by meters to kilometers over time if ignored. Station keeping is gentle steering so spacing, coverage, and safety stay intact, like staying in lane on a highway. Public materials describe daily caretaking for dense LEO fleets.',
    moduleIds: ['m4'],
    relatedIds: ['ion-thruster', 'deorbit'],
  },
  {
    id: 'ion-thruster',
    term: 'Ion thruster',
    short: 'Electric propulsion that gives a gentle, efficient push for a long time.',
    body: 'Thrust is small compared with chemical rockets (think continuous gentle push, not a big kick), but very fuel efficient for months of orbit raising and years of station keeping. Public Starlink materials discuss thrusters for raise, caretaking, and end of life. The teaching idea is efficient low thrust, not brand chemistry.',
    moduleIds: ['m4'],
    relatedIds: ['station-keeping', 'orbit-raise'],
  },
  {
    id: 'deorbit',
    term: 'Deorbit',
    short: 'Leaving service orbit so the satellite reenters and is disposed of.',
    body: 'Critical for space safety when thousands of satellites share low orbit. Lower altitudes can shorten passive decay (falling from drag) from years toward months if thrusters fail, depending on height and solar conditions. U.S. FCC licensing moved toward disposal as soon as practical and within 5 years after end of mission for licensees. That is national licensing, not a global space police force.',
    moduleIds: ['m4', 'opt-debris'],
    relatedIds: ['station-keeping', 'shell'],
  },
  {
    id: 'waypoint',
    term: 'Waypoint (orbit)',
    short: 'A temporary parking height (km) used while raising or moving a satellite into place.',
    body: 'After launch, satellites often climb in stages measured in kilometers of altitude. Waypoints help deconflict traffic and line up orbital elements before joining the final service shell.',
    moduleIds: ['m4'],
    relatedIds: ['orbit-raise', 'shell'],
  },
  {
    id: 'orbit-raise',
    term: 'Orbit raising',
    short: 'Climbing from the drop off height toward the service shell (altitude in km).',
    body: 'Rockets often insert satellites lower than the final operating height. Electric thrusters then raise altitude over days or longer (sometimes weeks depending on design and atmosphere) before the satellite enters service.',
    moduleIds: ['m4'],
    relatedIds: ['waypoint', 'ion-thruster'],
  },
  {
    id: 'phased-array',
    term: 'Phased array',
    short: 'An antenna made of many small elements that steers its beam electronically.',
    body: 'By adjusting timing (phase) across elements, the combined radio beam points without swinging a heavy dish with motors. That is key for flat LEO user terminals that track satellites moving at several km/s across the sky. Analogy: a stadium wave of people standing up at slightly different times.',
    moduleIds: ['m6'],
    relatedIds: ['beam-steering', 'user-terminal'],
  },
  {
    id: 'handoff',
    term: 'Handoff (handover)',
    short: 'Switching a user from one serving satellite to another (often many times per hour in LEO).',
    body: 'Required in LEO because usable passes last only minutes. Good systems aim to switch smoothly when two satellites are usable (make before break). Geometry forces handovers. Load and policy can also change who serves you. Users may notice rare blips; the lab counts handoffs as discrete events for teaching.',
    moduleIds: ['m6', 'm8'],
    relatedIds: ['elevation', 'user-terminal', 'pass'],
  },
  {
    id: 'elevation',
    term: 'Elevation angle',
    short: 'How high a satellite sits above your local horizon, in degrees (0° to 90°).',
    body: '0° is on the horizon. 90° is straight overhead. Networks often require a minimum elevation such as about 25° (policy and filings vary by system and latitude). Low elevation means a longer path through air and more chance of trees or roofs in the way. Higher minimums shrink usable sky. The lab’s default min elevation is 25°.',
    moduleIds: ['m6'],
    relatedIds: ['handoff', 'footprint', 'coverage-gap', 'obstruction'],
  },
  {
    id: 'user-terminal',
    term: 'User terminal',
    short: 'The customer antenna and modem on the ground (for example a flat Starlink dish).',
    body: 'It establishes and maintains the radio link to serving satellites and usually provides Ethernet or WiFi to your devices. Modern LEO systems often use electronically steered beams so the flat panel can track without a big motorized dish. Install needs a clear view of the sky above the network’s min elevation.',
    moduleIds: ['m6'],
    relatedIds: ['phased-array', 'handoff', 'obstruction'],
  },
  {
    id: 'footprint',
    term: 'Footprint',
    short: 'The region on Earth a satellite can serve at a given moment (area, not a single point).',
    body: 'Higher altitude generally means a larger footprint but more delay (more ms of light time). LEO footprints are smaller and move quickly as satellites orbit, which is why you need many of them for continuous service. Size is geometry plus the min elevation rule, not a fixed country border.',
    moduleIds: ['m2', 'm5', 'm6'],
    relatedIds: ['elevation', 'coverage-gap'],
  },
  {
    id: 'isl',
    term: 'ISL (inter satellite link)',
    short: 'A communications link between satellites, often with lasers at multi Gbps class rates.',
    body: 'ISLs let traffic hop through a space mesh before descending to a ground gateway. That helps oceans, poles, and places with few ground stations. Public Starlink materials describe optical ISLs at high data rates (marketing cites up to about 200 Gbps class links). Details of routing software stay proprietary. In this course, hop count is a first model; weighted delay is a better floor in ms.',
    moduleIds: ['m7'],
    relatedIds: ['gateway', 'space-mesh', 'routing'],
  },
  {
    id: 'gateway',
    term: 'Gateway (ground station)',
    short: 'A ground site that connects the satellite network to the ordinary Internet via fiber.',
    body: 'Think of a highway on ramp: antennas, radio gear, and fiber backhaul (often multi Gbps class). Almost every consumer bit still needs an exit onto the terrestrial Internet. Gateways are scarce. Lasers between satellites can reach a distant gateway, but they do not make gateways free or infinite. Congestion at a busy gateway can add queue delay in ms even when a satellite is overhead.',
    moduleIds: ['m7'],
    relatedIds: ['isl', 'ground-station', 'bent-pipe'],
  },
  {
    id: 'routing',
    term: 'Routing',
    short: 'Choosing paths for packets through a network (often measured in hops or delay).',
    body: 'In LEO systems, routing may use user links, ISLs, and gateways on a graph that changes as satellites move. First models count hops; better toy models minimize total delay in milliseconds. Exact operator algorithms are proprietary. This course teaches the problem class: a time varying network.',
    moduleIds: ['m7', 'm8'],
    relatedIds: ['isl', 'space-mesh', 'hop'],
  },
  {
    id: 'bent-pipe',
    term: 'Bent pipe',
    short: 'A design where the satellite mainly relays traffic, like a radio mirror.',
    body: 'Classic mental model for GEO internet: user ↔ satellite ↔ gateway ↔ Internet. The satellite amplifies and retransmits without deep processing. Smarter (regenerative) payloads can decode and route onboard. Real systems sit on a spectrum between those poles. Path length still sets a light time floor in ms either way.',
    moduleIds: ['m2', 'm7'],
    relatedIds: ['gateway', 'regenerative'],
  },
  {
    id: 'regenerative',
    term: 'Regenerative payload',
    short: 'Onboard processing that can decode, switch, or route traffic in space.',
    body: 'Contrasts with a simple bent pipe relay. Regenerative designs pair naturally with multi hop mesh routing, at the cost of complexity and power. We teach the idea, not any vendor’s exact stack. Processing can add small delays (often fractions of a ms to a few ms per hop in principle), but geometry and queues often dominate user feel.',
    moduleIds: ['m7'],
    relatedIds: ['bent-pipe', 'isl', 'routing'],
  },
  {
    id: 'coverage-gap',
    term: 'Coverage gap',
    short: 'A time or place with no usable satellite in view (offline periods).',
    body: 'Shows up in sparse fleets or with strict elevation rules. Measured as offline time or fraction (for example percent of samples with no sat above min elevation). Mega constellations are designed to minimize gaps for target users. Remember: no gap (online) is not the same as lots of capacity (Mbps available to you).',
    moduleIds: ['m3', 'm5'],
    relatedIds: ['constellation', 'elevation'],
  },
  {
    id: 'beam-steering',
    term: 'Beam steering',
    short: 'Pointing antenna energy toward a chosen direction (angles in degrees).',
    body: 'Can be mechanical (motors swing a dish) or electronic (phased arrays change timing). Electronic steering is what makes flat LEO terminals practical when satellites cross the sky in minutes. Practical scan ranges are limited; very low elevation can be hard for flat panels.',
    moduleIds: ['m6'],
    relatedIds: ['phased-array'],
  },
  {
    id: 'ground-station',
    term: 'Ground station',
    short: 'Another name for gateway facilities that link space to terrestrial networks.',
    body: 'Houses antennas, radio equipment, and fiber connectivity for backhaul (the fat pipe into the rest of the Internet, often multi Gbps). Same role as gateway in this course.',
    moduleIds: ['m7'],
    relatedIds: ['gateway'],
  },
  {
    id: 'space-mesh',
    term: 'Space mesh',
    short: 'A network formed by satellites linked to each other (for example with lasers).',
    body: 'Enables multi hop routing in orbit before traffic reaches a ground gateway. Useful when the nearest fiber on ramp is far away. Teaching models start with hop counts, then weighted delays in ms. The real topology changes every minute as geometry changes.',
    moduleIds: ['m7'],
    relatedIds: ['isl', 'routing'],
  },
  {
    id: 'scheduling',
    term: 'Scheduling (beams and resources)',
    short: 'Deciding which users and beams get radio resources when (time and spectrum shares).',
    body: 'Spectrum (MHz of bandwidth), power (watts), and beam time are limited. LEO systems must share them across many users and moving cells. Exact schedules are proprietary. The teaching idea is scarcity and sharing: your Mbps can drop at busy hours even when you stay online.',
    moduleIds: ['m8'],
    relatedIds: ['performance', 'phased-array', 'capacity-density'],
  },
  {
    id: 'performance',
    term: 'Performance (network)',
    short: 'What users feel: delay (ms), speed (Mbps), loss (%), and stability.',
    body: 'Performance is a mix of metrics: latency and RTT in milliseconds, throughput in Mbps, packet loss as a percent, and jitter as how much delay wobbles. It emerges from geometry, radio, routing, congestion, and handovers, not from one subsystem alone. Separate the geometric light time floor from mean RTT and outages.',
    moduleIds: ['m8'],
    relatedIds: ['latency', 'bandwidth', 'rtt', 'jitter'],
  },
  {
    id: 'jitter',
    term: 'Jitter',
    short: 'How much delay wobbles over time, usually measured in milliseconds.',
    body: 'If RTT jumps between 30 ms and 80 ms, that variation is jitter. Interactive apps care about smooth timing, not only average RTT. Handoffs, queues, path changes, and radio conditions can spike delay even when the pure light time floor is only a few ms.',
    moduleIds: ['m1', 'm8'],
    relatedIds: ['latency', 'rtt', 'handoff', 'performance'],
  },
  {
    id: 'ku-band',
    term: 'Ku band',
    short: 'A microwave radio band roughly 12 to 18 GHz (billions of cycles per second).',
    body: 'Frequency is measured in gigahertz (GHz). Higher frequency bands can support more capacity (Mbps/Gbps potential) with smaller antennas, with different weather sensitivity than lower bands. Exact channel maps are regulatory and operator details. This course teaches band class ideas, not reverse engineered tables.',
    moduleIds: ['m6', 'm7'],
    relatedIds: ['ka-band', 'user-terminal'],
  },
  {
    id: 'ka-band',
    term: 'Ka band',
    short: 'A microwave band roughly 26 to 40 GHz, often used for high capacity feeder links.',
    body: 'Higher GHz means more bandwidth potential than Ku class bands, and more rain fade. Public materials associate higher bands with gateway side capacity on Starlink class systems. Treat that as a design pattern. Feeder links are the fat pipes between satellites and gateways.',
    moduleIds: ['m7'],
    relatedIds: ['ku-band', 'gateway', 'rain-fade'],
  },
  {
    id: 'rain-fade',
    term: 'Rain fade',
    short: 'Signal loss (weaker link, fewer dB of margin) when rain absorbs or scatters high frequency radio.',
    body: 'Gets worse at higher frequencies (Ka class and above). Engineers talk about margin in decibels (dB): extra strength kept in reserve. When rain uses up the margin, rates can drop (fewer Mbps) or the link can outage. Link design and site diversity help. It is physics, not a software bug.',
    moduleIds: ['m7'],
    relatedIds: ['ka-band', 'ku-band'],
  },
  {
    id: 'link-budget',
    term: 'Link budget',
    short: 'An accounting of power, gains, and losses (often in dB) that decides if a radio link works.',
    body: 'Distance, antenna gain, frequency, weather, and noise all enter the story. Gains and losses are often added in decibels (dB). Direct to cell is harder than dish broadband mainly because phone antennas have far less gain and power margin, so the same satellite geometry is a tougher radio problem.',
    moduleIds: ['m6', 'opt-dtc'],
    relatedIds: ['user-terminal', 'phased-array'],
  },
  {
    id: 'direct-to-cell',
    term: 'Direct to cell (DTC)',
    short: 'Satellite service aimed at ordinary phones, not dedicated dishes.',
    body: 'Different product class from dish broadband: tougher radio budgets (phone antennas are tiny), often partnered with mobile operators, often messaging first historically before richer data. Public Starlink planning places DTC shells in a lower altitude band (roughly the 330 to 370 km class in published EOY 2026 planning tables). Not the same as home dish internet speeds.',
    moduleIds: ['opt-dtc'],
    relatedIds: ['link-budget', 'shell', 'user-terminal'],
  },
  {
    id: 'slant-range',
    term: 'Slant range',
    short: 'Straight line distance from user to satellite in km (not just altitude).',
    body: 'At low elevation the path through space and air is longer than the satellite’s height above Earth. Example: a sat at 550 km altitude can have a slant range of well over 1,000 km near the edge of the usable sky. Light time and radio budgets use slant range: more km means more ms of delay and a weaker free space signal.',
    moduleIds: ['m2', 'm6', 'opt-math'],
    relatedIds: ['elevation', 'propagation-delay'],
  },
  {
    id: 'sidereal-day',
    term: 'Sidereal day',
    short: 'Earth’s rotation period relative to the stars (about 23 hours 56 minutes).',
    body: 'GEO orbital period matches a sidereal day so the satellite stays fixed over one longitude. That is about 4 minutes shorter than the 24 hour solar day you use for daily life. Optional detail for precision lovers.',
    moduleIds: ['m2', 'opt-math'],
    relatedIds: ['geo', 'orbital-period'],
  },
  {
    id: 'pass',
    term: 'Pass',
    short: 'The time window when a satellite is usable above a minimum elevation (often minutes).',
    body: 'LEO passes last only minutes for a given user and min elevation (sometimes under 10 minutes of usable high elevation time per pass, depending on geometry). Continuous service stitches many passes from many satellites using handovers. The lab and code alongs can count contact windows as discrete samples.',
    moduleIds: ['m6'],
    relatedIds: ['elevation', 'handoff'],
  },
  {
    id: 'ephemeris',
    term: 'Ephemeris',
    short: 'A predicted timeline of where a satellite will be (positions over time).',
    body: 'Operators and catalogs publish ephemerides so others can predict close approaches and schedule observations. Updates may be frequent in LEO because drag and uncertainty grow quickly. Accuracy matters for collision avoidance in dense LEO. Positions are usually in km and time in UTC.',
    moduleIds: ['opt-debris', 'm4'],
    relatedIds: ['station-keeping', 'deorbit'],
  },
  {
    id: 'kessler',
    term: 'Kessler syndrome',
    short: 'A cascade idea: collisions create debris that causes more collisions.',
    body: 'The physics of cascading debris is a real risk model. Relative speeds in LEO are several km/s, so even small fragments can damage satellites. Whether we are “in cascade now” is debated and model dependent. Prefer careful language like “rising conjunction risk” unless you are teaching the cascade concept itself.',
    moduleIds: ['opt-debris'],
    relatedIds: ['deorbit', 'ephemeris'],
  },
  {
    id: 'spot-beam',
    term: 'Spot beam',
    short: 'A focused radio beam covering a limited ground cell (not the whole footprint).',
    body: 'LEO broadband systems serve users with many small beams, like cell towers in the sky rather than one giant megaphone. Cell sizes can be kilometers to tens of kilometers across depending on design. That multiplies capacity by reusing frequencies, and creates scheduling and interference as design problems.',
    moduleIds: ['m5', 'm6'],
    relatedIds: ['capacity-density', 'phased-array', 'footprint'],
  },
  {
    id: 'capacity-density',
    term: 'Capacity density',
    short: 'How much shared user throughput a region can support (for example Mbps per area), not just whether satellites are visible.',
    body: 'Coverage is geometry: is a usable satellite in the sky? Capacity is sharing: spectrum (MHz), power, beams, and how many neighbors use them. Dense sky can still feel slow at dinner time under load even if you stay online. Throughput is felt in Mbps; coverage is felt as online vs offline.',
    moduleIds: ['m5', 'm8'],
    relatedIds: ['spot-beam', 'coverage-gap', 'bandwidth'],
  },
  {
    id: 'obstruction',
    term: 'Obstruction',
    short: 'Something blocking the line of sight between your terminal and the satellite.',
    body: 'Trees, roofs, hills, and vehicle bodies commonly cause outages even when a map says a satellite is above the minimum elevation in degrees. Clear field of view is part of the system. Install tools often estimate blocked sky as a percent of the view above the min elevation mask.',
    moduleIds: ['m6'],
    relatedIds: ['elevation', 'pass', 'user-terminal'],
  },
]

export function getTerm(id: string): GlossaryTerm | undefined {
  return GLOSSARY.find((t) => t.id === id)
}

export function getRelatedTerms(id: string): GlossaryTerm[] {
  const term = getTerm(id)
  if (!term?.relatedIds?.length) return []
  return term.relatedIds.map(getTerm).filter(Boolean) as GlossaryTerm[]
}
